### PR TITLE
(Update) torrent.js config

### PR DESCRIPTION
**Pull request by HDVinnie**
- set showMenuHeaderForGuest, showFooterCountInfoForGuest, showDemoSignMessage to false by default. Seeing MEAN is aimed for private tracker use it would be reasonable to not show this to guest.

### CODE REVIEW

**Comment by taobataoma** [comment]
@HDVinnie hi, HDVinnie, How are you? your UNIT3D is so beautiful!

**Comment by HDVinnie** [comment]
@taobataoma  Im not to bad. You? 
Thanks for kind words about UNIT3D. 
meanTorrent is a great project. Wish I knew more JS. Best of luck to you.

**Comment by HDVinnie** [comment]
@taobataoma is something wrong with demo login info? Says invalid.

**Comment by taobataoma** [comment]
@HDVinnie hi, already ok now!

**Pull request closed without merging**
