### PR TITLE
feat(torrents): Add private tracker fields into torrent file

### PR DESCRIPTION
**Pull request by gyakkun**
feat(torrents): Add private tracker fields into torrent file

Add private tracker adaptation into torrent file.
Private tracker usually will add the following fields in torrents it generates, changing the hash of the "info" filed (as the hash of torrent file) to avoid cheating check if user uploads torrent from other pt-sites directlly.
test_torrent

(enhancement)

### CODE REVIEW

**Comment by gyakkun** [comment]
Seems I forget to change the tab into soft-tab XD.

**Comment by taobataoma** [comment]
@gyakkun , thanks a lot.
I will merge this pull request later.
If you come form china, please join our QQ Group: 291843550, then we can talk with chinese.

**Comment by gyakkun** [comment]
是学生.. 还只是个初学者, 可能没精力投入开发, 如果不介意的话我就加进去吧。有Bug还是会直接在这里开issue或者pr。
同学又报了一个bug, 说是如果原始种子的tracker多于一个, announce设置会失效, 在
```javascript
            torrent.metadata.announce = announce;
```
前加上这个就行了

```javascript
            if (!!torrent.metadata['announce-list']) {
              delete torrent.metadata['announce-list'];
            }
```

**Comment by Shadowghost** [comment]
Changes seem to be merged already, so this should be closed.

**Pull request closed without merging**
